# Generated by Django 4.1.4 on 2023-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='static/user_profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_account',
            field=models.BooleanField(default=False),
        ),
    ]
