# Generated by Django 4.1.4 on 2023-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default='Тут пока ничего нет ;)'),
        ),
    ]
