# Generated by Django 4.1.4 on 2023-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='user_profiles/'),
        ),
    ]
