# Generated by Django 4.1.4 on 2023-04-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_image_useritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritems',
            name='item_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
