# Generated by Django 4.1.4 on 2023-04-27 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_useritems_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_dop1',
        ),
        migrations.AddField(
            model_name='image',
            name='image_dop2',
            field=models.ImageField(default='images/def_logo.jpg', upload_to='user_profiles/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_main',
            field=models.ImageField(default='images/def_logo.jpg', upload_to='user_profiles/'),
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='pictures',
        ),
        migrations.AddField(
            model_name='useritems',
            name='pictures',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
    ]
